"""Renders deploy/rbac.yaml: Homestead's permissions, and nothing else.

deploy/deploy.yaml installs everything, including the LAN address and storage
class someone chose at install. Applying it again to catch up on permissions
would put those back to the defaults, so the permissions are also published on
their own. This takes them from deploy.yaml word for word, comments included,
so the two cannot say different things; a test re-renders and compares.

    python scripts/render_rbac.py
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
KINDS = ("ServiceAccount", "ClusterRole", "ClusterRoleBinding", "Role", "RoleBinding")
HEADER = """# Homestead's permissions on their own, from deploy/deploy.yaml.
#
# Apply this once to an install from before 2.8.71 and
# Homestead keeps its permissions up to date itself from then on:
#
#   kubectl apply -f https://raw.githubusercontent.com/wjcloudy/homestead/<release>/deploy/rbac.yaml
#
# It changes no Deployment, Service or volume. Installed Homestead somewhere
# other than the lab namespace? Change the namespaces below to match.
# Generated by scripts/render_rbac.py; edit deploy/deploy.yaml instead.
"""


def render(text=None):
    text = text if text is not None else (ROOT / "deploy" / "deploy.yaml").read_text(encoding="utf-8")
    docs = [d.strip("\n") for d in re.split(r"(?m)^---\s*$", text)]
    kept = [d for d in docs if any(re.search(rf"(?m)^kind: {kind}\s*$", d) for kind in KINDS)]
    return HEADER + "---\n" + "\n---\n".join(kept) + "\n"


if __name__ == "__main__":
    (ROOT / "deploy" / "rbac.yaml").write_text(render(), encoding="utf-8", newline="\n")
    print("deploy/rbac.yaml")
