#!/usr/bin/env python3
"""Write deploy/nodeprobe.yaml from the description in homestead_probe.

The manifest people apply by hand and the objects Homestead installs itself are
the same objects, so only one of them is written by a person. This renders the
other. tests/test_node_probe_upgrade.py fails if the checked-in file and this
output disagree.

    python scripts/render_nodeprobe.py
"""
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "server"))

import homestead_probe as probe  # noqa: E402

HEADER = """# Homestead node probe (optional)
#
# Kubernetes reports no physical temperatures, host device inventory, per-disk
# throughput or drive health. This DaemonSet reports them to Homestead, which
# shows them on the node detail page.
#
#   kubectl apply -f deploy/nodeprobe.yaml
#
# Generated by scripts/render_nodeprobe.py from server/homestead_probe.py and
# the scripts in server/probe. Edit those, not this file.
#
"""

PLAIN = re.compile(r"[A-Za-z0-9_][A-Za-z0-9_./:@-]*\Z")


def scalar(value):
    if isinstance(value, bool):
        return "true" if value else "false"
    if value is None:
        return "null"
    if isinstance(value, int):
        return str(value)
    text = str(value)
    if text and PLAIN.match(text) and not text.endswith(":"):
        return text
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def emit(value, indent=0, lines=None):
    """Enough YAML for the shapes this manifest uses, and no more."""
    lines = [] if lines is None else lines
    pad = " " * indent
    if isinstance(value, dict):
        for key, item in value.items():
            if isinstance(item, str) and "\n" in item:
                lines.append(f"{pad}{key}: |")
                for line in item.rstrip("\n").split("\n"):
                    lines.append(f"{pad}  {line}" if line else "")
            elif isinstance(item, (dict, list)) and item:
                lines.append(f"{pad}{key}:")
                emit(item, indent + 2, lines)
            elif isinstance(item, (dict, list)):
                lines.append(f"{pad}{key}: " + ("{}" if isinstance(item, dict) else "[]"))
            else:
                lines.append(f"{pad}{key}: {scalar(item)}")
        return lines
    for item in value:
        if isinstance(item, dict):
            rendered = emit(item, indent + 2)
            first = rendered[0].lstrip()
            lines.append(f"{pad}- {first}")
            lines.extend(rendered[1:])
        else:
            lines.append(f"{pad}- {scalar(item)}")
    return lines


def render(version):
    documents = probe.manifest(version, namespace="lab")
    blocks = ["\n".join(emit(document)) for document in documents]
    return HEADER + "---\n".join(block.rstrip("\n") + "\n" for block in blocks)


def current_version():
    text = (ROOT / "server" / "server.py").read_text(encoding="utf-8")
    match = re.search(r'HOMESTEAD_VERSION = .*?"(\d+\.\d+\.\d+)"\)', text)
    return match.group(1) if match else "dev"


if __name__ == "__main__":
    target = ROOT / "deploy" / "nodeprobe.yaml"
    target.write_text(render(current_version()), encoding="utf-8")
    print(f"wrote {target.relative_to(ROOT)} for {current_version()}")
